### ISSUE TITLE
Angular CLI was not found despite npm being installed in prior step

### ISSUE THREAD

**Issue by WeyardWiz** [alexruizprado/azure-pipelines-angular-cli-task#13]
I created an Azure Build pipeline and as part of the agent job, i have an npm install task followed by the Angular CLI extension task. Everything works just fine up until the Angular CLI task...its complaining that npm needs to be installed, yet in the previous step it clearly was already installed!  

**_Angular CLI was not found. Remember to perform "npm install" before using the steps of the Angular CLI extension. Angular CLI extensions uses @angular/cli package located in the node_modules folder of an Angular application._**

![image](https://user-images.githubusercontent.com/43695586/101125801-1828f200-35c8-11eb-8b86-df2cc3d01d16.png)
![image](https://user-images.githubusercontent.com/43695586/101126019-984f5780-35c8-11eb-9553-f972184b89cc.png)
![image](https://user-images.githubusercontent.com/43695586/101126154-e2d0d400-35c8-11eb-9de8-7baef5a69414.png)

**Comment by WeyardWiz** [comment]
ok so apparently i had to add an extra custom npm task: `install -g @angular/cli`

![image](https://user-images.githubusercontent.com/43695586/101130659-ddc45280-35d1-11eb-83d3-ba9622d6fba8.png)

Now im getting a different error: **The build command requires to be run in an Angular project, but a project definition could not be found.**

**Comment by alexruizprado** [comment]
Hi Weyard, I think the issue is that you didn't provide the folder where the Angular project is located, that will be where the package.json folder is, side by side with angular.json etc. If you do, npm install will install angular cli, and the rest of the commands will work. So for all the steps make sure the working directory you set is where angular projects is located in the repo. The field is called “Path to the angular project root”, for the npm install step something else.

**Comment by WeyardWiz** [comment]
thanks alex! Just wanted to update in case someone runs into this issue again; all that is required for this to work is an npm task, and you MUST point the working directory to the Angular folder of the project, e.g. 
![image](https://user-images.githubusercontent.com/43695586/101400713-4b58d300-389f-11eb-9195-395148efeef1.png)

after that is done, you just point the path of the Angular CI task to the project folder as well and it will succeed 👍 
![image](https://user-images.githubusercontent.com/43695586/101401031-bd311c80-389f-11eb-99f0-fc50bfec2275.png)

**Comment by alexruizprado** [comment]
Thanks Wayard, glad it worked.
